version: "3.9"

services:
  cockroachdb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cockroachdb
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    restart: unless-stopped

volumes:
  cockroach-data: